# Generated by Django 5.1.3 on 2025-02-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='params',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='tool_type',
            field=models.CharField(choices=[('ADD_FEATURE', 'Add Feature'), ('DELETE_FEATURE', 'Delete Feature'), ('PCA', 'PCA'), ('TSNE', 't-sne'), ('UMAP', 'UMAP'), ('LINEAR_CURVEFITTING', 'Linear Curve Fitting'), ('POLYNOMIAL_CURVEFITTING', 'Polynomial Curve Fitting'), ('EXPONENTIAL_CURVEFITTING', 'Exponential Curve Fitting'), ('LINEAR_INTERPOLATION', 'Linear Interpolation'), ('POLYNOMIAL_INTERPOLATION', 'Polynomial Interpolation'), ('SPLINE_INTERPOLATION', 'Spline Interpolation'), ('LINEAR_EXTRAPOLATION', 'Linear Extrapolation'), ('POLYNOMIAL_EXTRAPOLATION', 'Polynomial Extrapolation'), ('EXPONENTIAL_EXTRAPOLATION', 'Exponential Extrapolation'), ('PEARSON_CORRELATION', 'Pearson correlation'), ('SPEARMAN_CORRELATION', 'Spearman correlation'), ('KENDALL_CORRELATION', 'Kendall correlation'), ('DATA_OVERSAMPLE', 'Data Oversample')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(default='csv', max_length=10),
        ),
    ]
