# Generated by Django 5.1.3 on 2025-02-11 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_auditlog_action_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='upload_time',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='file',
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='columns',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='mean_values',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='missing_values',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='params',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='tool_type',
            field=models.CharField(choices=[('ADD_FEATURE', 'Add Feature'), ('DELETE_FEATURE', 'Delete Feature'), ('PCA', 'PCA'), ('TSNE', 't-SNE'), ('UMAP', 'UMAP'), ('LINEAR_CURVEFITTING', 'Linear Curve Fitting'), ('POLYNOMIAL_CURVEFITTING', 'Polynomial Curve Fitting'), ('EXPONENTIAL_CURVEFITTING', 'Exponential Curve Fitting'), ('LINEAR_INTERPOLATION', 'Linear Interpolation'), ('POLYNOMIAL_INTERPOLATION', 'Polynomial Interpolation'), ('SPLINE_INTERPOLATION', 'Spline Interpolation'), ('LINEAR_EXTRAPOLATION', 'Linear Extrapolation'), ('POLYNOMIAL_EXTRAPOLATION', 'Polynomial Extrapolation'), ('EXPONENTIAL_EXTRAPOLATION', 'Exponential Extrapolation'), ('PEARSON_CORRELATION', 'Pearson correlation'), ('SPEARMAN_CORRELATION', 'Spearman correlation'), ('KENDALL_CORRELATION', 'Kendall correlation'), ('DATA_OVERSAMPLE', 'Data Oversample')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_path',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel')], max_length=10),
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('features', models.JSONField(default=list)),
                ('records', models.JSONField(default=list)),
                ('last_dataset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='api.dataset')),
                ('next_dataset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev', to='api.dataset')),
                ('uploaded_file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataset', to='api.uploadedfile')),
            ],
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dataset'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='dataset',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.dataset'),
        ),
    ]
